FROM ghcr.io/flavorjones/truffleruby:latest

RUN mkdir /app
WORKDIR /app

# RubyGems
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock
RUN bundle install

COPY . /app
RUN SECRET_KEY_BASE=aaaa bundle exec rails assets:precompile

CMD ["bundle", "exec", "puma", "-t", "0:16"]
