default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: incunabula_development
  host: localhost
  username: root
  password:

test:
  <<: *default
  database: incunabula_test
  host: localhost
  username: root
  password:

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
