on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install Gems
        uses: ruby/setup-ruby@v1.90.0
        with:
          bundler-cache: true

      - name: Run RSpec
        run: |
          bundle exec rspec
